// Map definitions — 10 different maps, randomly selected each game
// Terrain codes: G=grass, S=sand, W=water, E=elevation
// Each terrain string is 40 chars wide × 24 rows

// Helper: parse terrain strings into 2D array, auto-pad to 40 cols
function parseTerrain(rows) {
    return rows.map(row => {
        // Pad short rows with the last character used
        while (row.length < 40) row += row[row.length - 1];
        return row.slice(0, 40).split('');
    });
}

const map1_classic = {
    name: 'Classic',
    castleGX: 17, castleGY: 10,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 3, gy: 3 },
        { type: 'tree', variant: 2, gx: 7, gy: 5 },
        { type: 'tree', variant: 3, gx: 35, gy: 4 },
        { type: 'tree', variant: 1, gx: 33, gy: 18 },
        { type: 'bush', variant: 1, gx: 5, gy: 15 },
        { type: 'bush', variant: 2, gx: 30, gy: 8 },
        { type: 'rock', variant: 1, gx: 12, gy: 6 },
        { type: 'rock', variant: 2, gx: 25, gy: 16 },
        { type: 'deco', variant: 1, gx: 10, gy: 4 },
        { type: 'deco', variant: 2, gx: 28, gy: 12 },
    ],
    bridges: [],
};

const map2_lake = {
    name: 'Lake',
    castleGX: 5, castleGY: 10,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGWWWWWWWWGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGWWWWWWWWWWWGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGWWWWWWWWWWWWWGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGWWWWWWWWWWWWWGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGWWWWWWWWWWWWWWGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGWWWWWWWWWWWWWWWGGGGGGGGG',
        'GGGGGGGGGGGGGGGGWWWWWWWWWWWWWWWGGGGGGGGG',
        'GGGGGGGGGGGGGGGGWWWWWWWWWWWWWWGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGWWWWWWWWWWWWWGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGWWWWWWWWWWWWGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGWWWWWWWWWWGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGWWWWWWWWGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 2, gy: 2 },
        { type: 'tree', variant: 3, gx: 2, gy: 17 },
        { type: 'tree', variant: 2, gx: 13, gy: 3 },
        { type: 'tree', variant: 4, gx: 35, gy: 7 },
        { type: 'tree', variant: 1, gx: 36, gy: 15 },
        { type: 'bush', variant: 1, gx: 14, gy: 6 },
        { type: 'bush', variant: 3, gx: 33, gy: 11 },
        { type: 'bush', variant: 2, gx: 14, gy: 17 },
        { type: 'rock', variant: 1, gx: 15, gy: 5 },
        { type: 'rock', variant: 3, gx: 32, gy: 17 },
        { type: 'deco', variant: 7, gx: 12, gy: 9 },
        { type: 'deco', variant: 8, gx: 34, gy: 5 },
    ],
    bridges: [],
};

const map3_river = {
    name: 'River',
    castleGX: 17, castleGY: 4,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 3, gy: 1 },
        { type: 'tree', variant: 2, gx: 8, gy: 2 },
        { type: 'tree', variant: 3, gx: 30, gy: 1 },
        { type: 'tree', variant: 4, gx: 5, gy: 15 },
        { type: 'tree', variant: 1, gx: 33, gy: 18 },
        { type: 'tree', variant: 2, gx: 12, gy: 20 },
        { type: 'bush', variant: 1, gx: 15, gy: 14 },
        { type: 'bush', variant: 2, gx: 25, gy: 16 },
        { type: 'rock', variant: 1, gx: 10, gy: 13 },
        { type: 'rock', variant: 2, gx: 28, gy: 7 },
    ],
    bridges: [
        { gx: 9, gy: 9, direction: 'horizontal' },
        { gx: 29, gy: 9, direction: 'horizontal' },
    ],
};

const map4_forest = {
    name: 'Forest',
    castleGX: 17, castleGY: 10,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ]),
    decorations: [
        // Dense tree border - top
        { type: 'tree', variant: 1, gx: 2, gy: 1 },
        { type: 'tree', variant: 2, gx: 5, gy: 1 },
        { type: 'tree', variant: 3, gx: 8, gy: 2 },
        { type: 'tree', variant: 4, gx: 11, gy: 1 },
        { type: 'tree', variant: 1, gx: 14, gy: 2 },
        { type: 'tree', variant: 2, gx: 25, gy: 1 },
        { type: 'tree', variant: 3, gx: 28, gy: 2 },
        { type: 'tree', variant: 4, gx: 31, gy: 1 },
        { type: 'tree', variant: 1, gx: 34, gy: 1 },
        { type: 'tree', variant: 2, gx: 37, gy: 2 },
        // Dense tree border - bottom
        { type: 'tree', variant: 3, gx: 2, gy: 20 },
        { type: 'tree', variant: 4, gx: 5, gy: 21 },
        { type: 'tree', variant: 1, gx: 8, gy: 20 },
        { type: 'tree', variant: 2, gx: 11, gy: 21 },
        { type: 'tree', variant: 3, gx: 25, gy: 20 },
        { type: 'tree', variant: 4, gx: 28, gy: 21 },
        { type: 'tree', variant: 1, gx: 31, gy: 20 },
        { type: 'tree', variant: 2, gx: 34, gy: 21 },
        { type: 'tree', variant: 3, gx: 37, gy: 20 },
        // Dense tree border - left
        { type: 'tree', variant: 4, gx: 1, gy: 5 },
        { type: 'tree', variant: 1, gx: 2, gy: 8 },
        { type: 'tree', variant: 2, gx: 1, gy: 11 },
        { type: 'tree', variant: 3, gx: 2, gy: 14 },
        { type: 'tree', variant: 4, gx: 1, gy: 17 },
        // Dense tree border - right
        { type: 'tree', variant: 1, gx: 37, gy: 5 },
        { type: 'tree', variant: 2, gx: 38, gy: 8 },
        { type: 'tree', variant: 3, gx: 37, gy: 11 },
        { type: 'tree', variant: 4, gx: 38, gy: 14 },
        { type: 'tree', variant: 1, gx: 37, gy: 17 },
        // Bush clusters
        { type: 'bush', variant: 1, gx: 4, gy: 4 },
        { type: 'bush', variant: 2, gx: 6, gy: 3 },
        { type: 'bush', variant: 3, gx: 35, gy: 4 },
        { type: 'bush', variant: 4, gx: 4, gy: 19 },
        { type: 'bush', variant: 1, gx: 35, gy: 19 },
        // Stumps
        { type: 'stump', variant: 1, gx: 10, gy: 8 },
        { type: 'stump', variant: 2, gx: 30, gy: 15 },
        // Mushrooms
        { type: 'deco', variant: 1, gx: 6, gy: 7 },
        { type: 'deco', variant: 2, gx: 33, gy: 6 },
        { type: 'deco', variant: 3, gx: 7, gy: 16 },
    ],
    bridges: [],
};

const map5_rockyHills = {
    name: 'Rocky Hills',
    castleGX: 17, castleGY: 10,
    terrain: parseTerrain([
        'EEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEEGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEEGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEEEGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEEGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEGG',
    ]),
    decorations: [
        { type: 'rock', variant: 1, gx: 10, gy: 5 },
        { type: 'rock', variant: 2, gx: 12, gy: 7 },
        { type: 'rock', variant: 3, gx: 8, gy: 9 },
        { type: 'rock', variant: 4, gx: 25, gy: 15 },
        { type: 'rock', variant: 1, gx: 27, gy: 17 },
        { type: 'rock', variant: 2, gx: 23, gy: 14 },
        { type: 'tree', variant: 1, gx: 15, gy: 3 },
        { type: 'tree', variant: 3, gx: 20, gy: 19 },
        { type: 'bush', variant: 1, gx: 13, gy: 11 },
        { type: 'bush', variant: 2, gx: 22, gy: 9 },
        { type: 'deco', variant: 4, gx: 11, gy: 8 },
        { type: 'deco', variant: 5, gx: 26, gy: 16 },
    ],
    bridges: [],
};

const map6_coastal = {
    name: 'Coastal',
    castleGX: 8, castleGY: 10,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWWW',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGSSSSWWWWWWWWW',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 3, gy: 3 },
        { type: 'tree', variant: 2, gx: 6, gy: 6 },
        { type: 'tree', variant: 3, gx: 3, gy: 16 },
        { type: 'tree', variant: 4, gx: 15, gy: 4 },
        { type: 'tree', variant: 1, gx: 18, gy: 18 },
        { type: 'bush', variant: 1, gx: 20, gy: 8 },
        { type: 'bush', variant: 2, gx: 22, gy: 14 },
        { type: 'rock', variant: 1, gx: 24, gy: 6 },
        { type: 'rock', variant: 2, gx: 25, gy: 18 },
        { type: 'deco', variant: 6, gx: 23, gy: 10 },
    ],
    bridges: [],
};

const map7_twinLakes = {
    name: 'Twin Lakes',
    castleGX: 17, castleGY: 10,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGWWWWWWWGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGWWWWWWWGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWWGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWWWWGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWWWWGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWWGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 4, gy: 1 },
        { type: 'tree', variant: 2, gx: 3, gy: 9 },
        { type: 'tree', variant: 3, gx: 35, gy: 3 },
        { type: 'tree', variant: 4, gx: 36, gy: 13 },
        { type: 'bush', variant: 1, gx: 6, gy: 8 },
        { type: 'bush', variant: 2, gx: 14, gy: 3 },
        { type: 'bush', variant: 3, gx: 24, gy: 15 },
        { type: 'bush', variant: 4, gx: 33, gy: 22 },
        { type: 'rock', variant: 1, gx: 5, gy: 14 },
        { type: 'rock', variant: 3, gx: 34, gy: 9 },
        { type: 'deco', variant: 10, gx: 13, gy: 7 },
        { type: 'deco', variant: 11, gx: 24, gy: 22 },
    ],
    bridges: [],
};

const map8_valley = {
    name: 'Valley',
    castleGX: 17, castleGY: 11,
    terrain: parseTerrain([
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 3, gy: 6 },
        { type: 'tree', variant: 2, gx: 36, gy: 7 },
        { type: 'tree', variant: 3, gx: 5, gy: 16 },
        { type: 'tree', variant: 4, gx: 34, gy: 17 },
        { type: 'rock', variant: 1, gx: 10, gy: 6 },
        { type: 'rock', variant: 2, gx: 28, gy: 17 },
        { type: 'rock', variant: 3, gx: 15, gy: 15 },
        { type: 'rock', variant: 4, gx: 25, gy: 8 },
        { type: 'bush', variant: 1, gx: 8, gy: 9 },
        { type: 'bush', variant: 2, gx: 30, gy: 14 },
        { type: 'deco', variant: 16, gx: 20, gy: 8 },
        { type: 'deco', variant: 17, gx: 12, gy: 13 },
    ],
    bridges: [],
};

const map9_swamp = {
    name: 'Swamp',
    castleGX: 10, castleGY: 10,
    terrain: parseTerrain([
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGWWWGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGWWWWWGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGWWWGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGWWWGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGWWWWWGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGWWWGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGWWWGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGWWWWWGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGWWWGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ]),
    decorations: [
        { type: 'bush', variant: 1, gx: 5, gy: 3 },
        { type: 'bush', variant: 2, gx: 8, gy: 5 },
        { type: 'bush', variant: 3, gx: 18, gy: 2 },
        { type: 'bush', variant: 4, gx: 30, gy: 4 },
        { type: 'bush', variant: 1, gx: 7, gy: 10 },
        { type: 'bush', variant: 2, gx: 25, gy: 11 },
        { type: 'bush', variant: 3, gx: 33, gy: 8 },
        { type: 'bush', variant: 4, gx: 16, gy: 14 },
        { type: 'bush', variant: 1, gx: 35, gy: 16 },
        { type: 'bush', variant: 2, gx: 6, gy: 19 },
        { type: 'tree', variant: 1, gx: 2, gy: 1 },
        { type: 'tree', variant: 3, gx: 37, gy: 2 },
        { type: 'tree', variant: 2, gx: 36, gy: 20 },
        { type: 'tree', variant: 4, gx: 2, gy: 20 },
        { type: 'stump', variant: 1, gx: 20, gy: 10 },
        { type: 'stump', variant: 3, gx: 30, gy: 14 },
        { type: 'deco', variant: 1, gx: 9, gy: 7 },
        { type: 'deco', variant: 7, gx: 22, gy: 15 },
        { type: 'deco', variant: 8, gx: 15, gy: 9 },
    ],
    bridges: [],
};

const map10_desertOasis = {
    name: 'Desert Oasis',
    castleGX: 17, castleGY: 10,
    terrain: parseTerrain([
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSGGGGGSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSGGGGGGGSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSGGGWWWGGGSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSGGGWWWGGGSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSGGGGGGGSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSGGGGGSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
        'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
    ]),
    decorations: [
        { type: 'tree', variant: 1, gx: 17, gy: 9 },
        { type: 'tree', variant: 2, gx: 21, gy: 10 },
        { type: 'tree', variant: 3, gx: 16, gy: 13 },
        { type: 'bush', variant: 1, gx: 18, gy: 14 },
        { type: 'bush', variant: 2, gx: 22, gy: 9 },
        { type: 'rock', variant: 1, gx: 5, gy: 5 },
        { type: 'rock', variant: 2, gx: 33, gy: 4 },
        { type: 'rock', variant: 3, gx: 8, gy: 18 },
        { type: 'rock', variant: 4, gx: 30, gy: 19 },
        { type: 'deco', variant: 14, gx: 12, gy: 8 },
        { type: 'deco', variant: 15, gx: 26, gy: 16 },
        { type: 'deco', variant: 4, gx: 7, gy: 12 },
        { type: 'deco', variant: 5, gx: 32, gy: 10 },
    ],
    bridges: [],
};

export const MAP_DEFINITIONS = [
    map1_classic,
    map2_lake,
    map3_river,
    map4_forest,
    map5_rockyHills,
    map6_coastal,
    map7_twinLakes,
    map8_valley,
    map9_swamp,
    map10_desertOasis,
];

export function getRandomMap() {
    const index = Math.floor(Math.random() * MAP_DEFINITIONS.length);
    return MAP_DEFINITIONS[index];
}
